apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  serviceName: "mariadb"
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb
        env:
        - name: MARIADB_ROOT_PASSWORD
          value : root123
        image: mariadb:10.2.38
        imagePullPolicy: Always
        livenessProbe:
          initialDelaySeconds: 60
          periodSeconds: 10
          tcpSocket:
            port: 3306
          timeoutSeconds: 3
        ports:
        - containerPort: 3306
        readinessProbe:
          initialDelaySeconds: 60
          periodSeconds: 10
          tcpSocket:
            port: 3306
          timeoutSeconds: 3
        resources:
          limits:
            cpu: 350m
            memory: 680Mi
          requests:
            cpu: 50m
            memory: 256Mi
      enableServiceLinks: false
...