apiVersion: v1
kind: Service
metadata:
  name: mariadb
spec:
  ports:
  - name: "tcp-3306"
    port: 3306
    targetPort: 3306
  selector:
    app: mariadb
  type: ClusterIP
status:
  loadBalancer: {}
...