apiVersion: v1
kind: Service
metadata:
  name: ticket-manager
spec:
  ports:
  - name: "http-8080"
    port: 8080
    targetPort: 8080
  selector:
    app: ticket-manager
  type: ClusterIP
status:
  loadBalancer: {}
...